import pool from '../lib/db'
import { RuleNode } from '../lib/types'

const cnRules: RuleNode[] = [
  {
    id: 'CN-PIPL-38',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 38',
    dimension: 'cross_border_transfer',
    requirement_type: 'mandatory',
    mechanism: ['security_assessment', 'standard_contract', 'certification'],
    text_en: 'Where a personal information processor needs to provide personal information overseas due to business needs, it shall meet one of the following conditions: passing a security assessment organized by the national cyberspace authority; obtaining a personal information protection certification from a professional institution; concluding a contract with the overseas recipient in accordance with standard contracts formulated by the national cyberspace authority.',
    text_zh: '个人信息处理者因业务等需要，确需向中华人民共和国境外提供个人信息的，应当具备下列条件之一：通过国家网信部门组织的安全评估；经专业机构进行个人信息保护认证；按照国家网信部门制定的标准合同与境外接收方订立合同。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-40',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 40',
    dimension: 'cross_border_transfer',
    requirement_type: 'mandatory',
    mechanism: ['security_assessment'],
    text_en: 'Critical information infrastructure operators and personal information processors that process personal information reaching the quantity threshold specified by the national cyberspace authority shall store personal information collected and generated within China domestically. If it is truly necessary to provide such information overseas, a security assessment shall be conducted.',
    text_zh: '关键信息基础设施运营者和处理个人信息达到国家网信部门规定数量的个人信息处理者，应当将在中华人民共和国境内收集和产生的个人信息存储在境内。确需向境外提供的，应当通过国家网信部门组织的安全评估。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-13',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 13',
    dimension: 'consent',
    requirement_type: 'mandatory',
    mechanism: ['individual_consent', 'contract_necessity', 'legal_obligation'],
    text_en: 'Personal information processors may process personal information only when one of the following circumstances applies: obtaining the individual consent of the individual concerned; necessary for the conclusion or performance of a contract to which the individual is a party, or necessary for carrying out human resources management; necessary for fulfilling statutory duties or statutory obligations; necessary for responding to public health emergencies; processing is carried out within a reasonable scope for news reporting or public interest supervision.',
    text_zh: '符合下列情形之一的，个人信息处理者方可处理个人信息：取得个人的同意；为订立、履行个人作为一方当事人的合同所必需；为履行法定职责或者法定义务所必需；为应对突发公共卫生事件所必需；依照本法规定在合理的范围内处理个人自行公开或者其他已经合法公开的个人信息。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-39',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 39',
    dimension: 'cross_border_transfer',
    requirement_type: 'mandatory',
    mechanism: ['individual_consent', 'notice'],
    text_en: 'Where a personal information processor provides personal information overseas, it shall inform the individual of the name and contact information of the overseas recipient, the purpose and method of processing, the type of personal information, and the ways and procedures for the individual to exercise rights over the overseas recipient. Separate consent shall be obtained from the individual.',
    text_zh: '个人信息处理者向境外提供个人信息的，应当向个人告知境外接收方的名称或者姓名、联系方式、处理目的、处理方式、个人信息的种类以及个人向境外接收方行使本法规定权利的方式和程序等事项，并取得个人的单独同意。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-DSL-31',
    country: 'CN',
    law: 'Data Security Law (DSL)',
    article: 'Article 31',
    dimension: 'cross_border_transfer',
    requirement_type: 'mandatory',
    mechanism: ['security_assessment'],
    text_en: 'The security management of cross-border transfer of important data collected and generated by critical information infrastructure operators during operations within the territory of the People\'s Republic of China shall be subject to the provisions of the Cybersecurity Law of the People\'s Republic of China. The security management of cross-border data transfer by other data processors shall be formulated by the national cyberspace authority in conjunction with relevant authorities.',
    text_zh: '关键信息基础设施运营者在中华人民共和国境内运营中收集和产生的重要数据的出境安全管理，适用《中华人民共和国网络安全法》的规定；其他数据处理者在中华人民共和国境内运营中收集和产生的重要数据的出境安全管理办法，由国家网信部门会同国务院有关部门制定。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202106/7c9af12f51334a73b56d7938f99a788a.shtml',
    effective_date: '2021-09-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-CBDT-4',
    country: 'CN',
    law: 'Provisions on Promoting and Regulating Cross-Border Data Flows (CBDT)',
    article: 'Article 4',
    dimension: 'cross_border_transfer',
    requirement_type: 'conditional',
    mechanism: ['security_assessment_exemption'],
    text_en: 'Where a personal information processor provides personal information overseas and meets one of the following circumstances, it is not required to apply for a security assessment: data that does not contain personal information or important data; personal information that is not collected and generated within China; personal information that is necessary to be provided overseas for the conclusion or performance of a contract, and the total amount does not exceed 100,000 individuals.',
    text_zh: '个人信息处理者向境外提供个人信息，符合下列情形之一的，不需要申报数据出境安全评估：不包含个人信息或者重要数据的数据；非在境内收集和产生的个人信息；为订立、履行个人作为一方当事人的合同所必需出境的个人信息，且累计不超过10万人。',
    source_url: 'https://www.cac.gov.cn/2024-03/22/c_1712854558627335.htm',
    effective_date: '2024-03-22',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-51',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 51',
    dimension: 'security_assessment',
    requirement_type: 'mandatory',
    mechanism: ['technical_measures', 'organizational_measures'],
    text_en: 'Personal information processors shall adopt the following measures to ensure that personal information processing activities comply with laws and regulations and prevent unauthorized access, as well as leakage, tampering, and loss of personal information: formulating internal management systems and operating procedures; classifying personal information and implementing classified management; adopting corresponding technical security measures such as encryption and de-identification; reasonably determining the authority for personal information processing operations and regularly providing education and training for employees.',
    text_zh: '个人信息处理者应当根据个人信息的处理目的、处理方式、个人信息的种类以及对个人权益的影响、可能存在的安全风险等，采取下列措施确保个人信息处理活动符合法律、行政法规的规定，并防止未经授权的访问以及个人信息泄露、篡改、丢失。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-57',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 57',
    dimension: 'breach_notification',
    requirement_type: 'mandatory',
    mechanism: ['authority_notification', 'individual_notification'],
    text_en: 'Where a personal information leakage, tampering, or loss has occurred or may have occurred, the personal information processor shall immediately take remedial measures and notify the competent authority and the affected individuals. Where it is possible to take measures to effectively avoid the harm caused by the leakage, tampering, or loss, the personal information processor may not notify the individual; however, where the competent authority considers that notification is necessary, the personal information processor shall notify the individual.',
    text_zh: '发生或者可能发生个人信息泄露、篡改、丢失的，个人信息处理者应当立即采取补救措施，并通知履行个人信息保护职责的部门和受影响的个人。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-44',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 44',
    dimension: 'data_subject_rights',
    requirement_type: 'mandatory',
    mechanism: ['right_to_access', 'right_to_copy'],
    text_en: 'Individuals have the right to know about and to make decisions on the processing of their personal information, and have the right to restrict or refuse the processing of their personal information by others, except as otherwise provided by laws and administrative regulations.',
    text_zh: '个人对其个人信息的处理享有知情权、决定权，有权限制或者拒绝他人对其个人信息进行处理；法律、行政法规另有规定的除外。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
  {
    id: 'CN-PIPL-47',
    country: 'CN',
    law: 'Personal Information Protection Law (PIPL)',
    article: 'Article 47',
    dimension: 'data_subject_rights',
    requirement_type: 'mandatory',
    mechanism: ['right_to_deletion'],
    text_en: 'An individual may request the deletion of personal information under any of the following circumstances: the purpose of processing has been achieved, is impossible to achieve, or the personal information is no longer necessary for achieving the processing purpose; the personal information processor has ceased to provide the product or service, or the retention period has expired; the individual has withdrawn consent; the personal information processor has processed personal information in violation of laws, administrative regulations, or the agreement; other circumstances prescribed by laws and administrative regulations.',
    text_zh: '有下列情形之一的，个人信息处理者应当主动删除个人信息；个人信息处理者未删除的，个人有权请求删除：处理目的已实现、无法实现或者为实现处理目的不再必要；个人信息处理者停止提供产品或者服务，或者保存期限已届满；个人撤回同意；个人信息处理者违反法律、行政法规或者违反约定处理个人信息。',
    source_url: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml',
    effective_date: '2021-11-01',
    source_authority: 'official_law',
  },
]

async function seedCN() {
  const conn = await pool.getConnection()
  try {
    for (const rule of cnRules) {
      await conn.execute(
        `INSERT INTO rules (id, country, law, article, dimension, requirement_type, mechanism, text_en, text_zh, source_url, effective_date, source_authority)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE text_en = VALUES(text_en)`,
        [
          rule.id, rule.country, rule.law, rule.article,
          rule.dimension, rule.requirement_type,
          JSON.stringify(rule.mechanism),
          rule.text_en, rule.text_zh || null,
          rule.source_url, rule.effective_date, rule.source_authority,
        ]
      )
    }
    console.log(`✓ Seeded ${cnRules.length} CN rules`)
  } finally {
    conn.release()
    await pool.end()
  }
}

seedCN().catch(console.error)
